Remove default sensor_types
VoronDesign/Voron-2 pull request #349
Opened 2022-04-22 03:44 UTC by AndrewEllis93

- Remove default `sensor_type:` values to ensure that users are verifying their thermistors. Many users are just using the default values without actually checking.
- Add comments linking to Klipper thermistor list (so always up-to-date)
- Remove thermistor list at bottom of config files (if it exists - better to use the always up-to-date Klipper link)
- Hint at using "Generic 3950" for NTC 100k 3950, and also for Keenovo heaters
- Remove custom 3950 definition (if exists) - no longer necessary, Klipper thermistor accuracy bug has been fixed, and any new builders will be pulling a new version of Klipper.

2022-04-23 04:35 UTC, AndrewEllis93 commented
- Converted all tabs to white spaces, preserving alignment, so it displays correctly in all editors and on GitHub
- Commented out sensor_types - this makes the easier to understand (thanks for the idea Tetsunosuke)
![image](https://user-images.githubusercontent.com/34943186/164877513-59384317-f6bc-4661-9ca7-0df805c1c282.png)

2022-04-23 10:24 UTC, cbc02009 requested changes

2022-04-23 10:24 UTC, cbc02009 commented on firmware/klipper_configurations/Spider/Voron2_Spider_Config.cfg
> +    BED_MESH_CLEAR
Need a newline at the end of the file.

2022-04-23 19:35 UTC, AndrewEllis93 commented
Ensured newlines at the end of each file.
Removed 3950 footnotes (if any)

2022-04-23 19:42 UTC, AndrewEllis93 commented
Side note: these EOF newlines at the end don't seem to always display correctly in GitHub. When I download the raw files (not just view raw in browser), though, they are there.

2022-04-30 13:21 UTC, cbc02009 approved these changes

2022-04-30 13:22 UTC, raymondh2 approved these changes

2022-04-30 13:22 UTC, merged