Remove [SAVE|RESTORE]_GCODE_STATE from PRINT_END macro
VoronDesign/Voron-2 pull request #452
Opened 2023-10-27 17:37 UTC by voidtrance

The sample configuration for some boards contain PRINT_END macros that include [SAVE|RESTORE]_GCODE_STATE command in them.

Unfortunately, those commands may have a negative effect in that the macro tries to perform some safety moves between them to move the toolhead away from the print. However, when the GCode state is restore, Klipper will move the toolhead to the last position before the GCode state is save. This will negate the safety moves and put the toolhead back where it was.

Fix this by removing the [SAVE|RESTORE]_GCODE_STATE command.

2023-10-27 20:06 UTC, KiloQubit commented
`RESTORE_GCODE_STATE` does NOT move the toolhead back to its original position unless `MOVE=1` is specified, which it is not.

https://www.klipper3d.org/G-Codes.html#restore_gcode_state

2023-10-27 22:15 UTC, voidtrance commented
> `RESTORE_GCODE_STATE` does NOT move the toolhead back to its original position unless `MOVE=1` is specified, which it is not.
> 
> https://www.klipper3d.org/G-Codes.html#restore_gcode_state

You are correct. I'll change the commit text.

2023-11-08 18:20 UTC, voidtrance commented
I've updated the change to match the one already merged into the Trident repository.

2023-11-09 01:51 UTC, KiloQubit requested changes
Can you move the save_gcode_state back up to before the M400/G92?  That would also match the Trident configs.

2023-11-22 19:46 UTC, KiloQubit approved these changes

2023-11-22 19:46 UTC, merged