2 front decoration parts
VoronDesign/Voron-2 pull request #50
Opened 2019-10-24 00:09 UTC by underpk

19mm button and  Voron logo on gear fairing.

2019-10-30 05:59 UTC, TorinoFermic commented on Mods/README.md
> +- Add Voron logo on gear fairing
The link to other repo is not required when referencing these files. You instead use the `[Name of item where the stl is located](../mods/underpk)`
Then leave this link to your repo after these lines.

2019-10-30 05:59 UTC, TorinoFermic commented on Mods/underpk/README.md
> +- Add Voron logo on gear fairing
Ditto here.

2019-11-03 15:53 UTC, john-- commented
It appears there are some conflicts

2019-11-05 21:59 UTC, FHeilmann commented
Hey, I had a look at your two parts and I quite like the concept.

Here are a few minor tweaks I would suggest:

- The tabs on the buttons were not long enough to 'reach around the backside' of the skirt for me by about .2 to .3mm.

- The tabs in general just consist of 1-2 unsupported lines, which makes them fragile and prone to just snap off on first insertion. Since you went with a pretty solid press fit, I would suggest to either remove them altogether or beefing them up slightly (while also supporting them with a proper chamfer)

Cheers,
-Florian

2019-11-05 22:12 UTC, FHeilmann requested changes
Hey, I had a look at your two parts and I quite like the concept.

Here are a few minor tweaks I would suggest:

The tabs on the buttons were not long enough to 'reach around the backside' of the skirt for me by about .2 to .3mm.

The tabs in general just consist of 1-2 unsupported lines, which makes them fragile and prone to just snap off on first insertion. Since you went with a pretty solid press fit, I would suggest to either remove them altogether or beefing them up slightly (while also supporting them with a proper chamfer)

Cheers,
-Florian

edit: Also if you still have them, could you add the step files/f3d files for this mod?

edit2: regarding the conflicts. It's probably better to close this PR and start with a fresh copy of the current master branch.

2019-11-14 23:44 UTC, FHeilmann commented
We have moved all the mods to a new repository: https://github.com/VoronDesign/VoronUsers
Please resubmit your PR over there!

Thanks!

2019-11-21 09:12 UTC, FHeilmann commented
I'm going to close this for now. Feel free to resubmit this PR to the VoronUsers repository!

2019-11-21 09:12 UTC, closed without merging